### PR TITLE
fixed a little typo

### PR DESCRIPTION
**Pull request by Pythagorion**
Made 'Aways' to 'Always' in the item editor

### CODE REVIEW

**Comment by ZenBre4ker** [comment]
Not really up to date 🤣 
grafik

**Comment by TimGoll** [comment]
you see @Pythagorion there are many ways to update your fork :D

**Comment by TimGoll** [comment]
> Yes I see. I resolved (hopefully Ive done it right :D ) the conflict first. And now I will take care of my fork

take a look at the changes, due to your old fork, there are now strings added, that were removed by us. Either remove them manually, or redo this PR.

**Comment by Pythagorion** [comment]
Alright. I redo this PR. This should be the safest way to solve everything.

**Pull request closed without merging**
